constproductsdata = [
  {
    id: 1,
    name: "Placa de video asus rog strix Rtx 3080",
    price: "170.000$ ",
    marca: "asus",
    category: "placa de video",
    cardImg: "./assets/img/productos/rogstrix 3080.jpg",
  },
  {
    id: 2,
    name: "Placa de video Msi Rtx 3080Ti",
    price: "170.000$ ",
    marca: "Msi",
    category: "placa de video",
    cardImg: "./assets/img/productos/ventus.jpeg",
  },
  {
    id: 3,
    name: "Placa de video palit Rtx 3060",
    price: "170.000$ ",
    marca: "palit",
    category: "placa de video",
    cardImg: "./assets/img/productos/3060palit.jpg",
  },
  {
    id: 4,
    name: "Placa de video asus dual 3070",
    price: "130.000$ ",
    marca: "asus",
    category: "placa de video",
    cardImg: "./assets/img/productos/asusdual.jpeg",
  },

  {
    id: 5,
    name: "Placa de video gtx 1660 super",
    price: "170.000$ ",
    marca: "evga",
    category: "placa de video",
    cardImg: "./assets/img/productos/1660superjpg",
  },
  {
    id: 6,
    name: "Mouse logitech superlight",
    price: "24.000$ ",
    marca: "logitech",
    category: "perisféricos",
    cardImg: ,
  },
  {
    id: 7,
    name: "auriculares cloud flight",
    price: "28.000$ ",
    marca: "logitech",
    category: "perisféricos",
    cardImg: ,
  },
  {
    id: 8,
    name: "Mouse logitech g203",
    price: "8.000$ ",
    marca: "logitech",
    category: "perisféricos",
    cardImg: ,
  },
  {
    id: 9,
    name: "Teclado hyperx alloy fps pro",
    price: "17.000$ ",
    marca: "logitech",
    category: "perisféricos",
    cardImg: ,
  },
  {
    id: 10,
    name: "mousepad logitech g640",
    price: "7.456$ ",
    marca: "logitech",
    category: "perisféricos",
    cardImg: ,
  },
  {
    id: 11,
    name: "mousepad logitech g640",
    price: "7.456$ ",
    marca: "logitech",
    category: "perisféricos",
    cardImg: ,
  },
  {
    id: 12,
    name: "mousepad logitech g640",
    price: "7.456$ ",
    marca: "logitech",
    category: "perisféricos",
    cardImg: ,
  },
  {
    id: 13,
    name: "mousepad logitech g640",
    price: "7.456$ ",
    marca: "logitech",
    category: "perisféricos",
    cardImg: ,
  },
  {
    id: 14,
    name: "mousepad logitech g640",
    price: "7.456$ ",
    marca: "logitech",
    category: "perisféricos",
    cardImg: ,
  },
  {
    id: 15,
    name: "mousepad logitech g640",
    price: "7.456$ ",
    marca: "logitech",
    category: "perisféricos",
    cardImg: ,
  },
];
